name: pylon
description: "Anchor data in your widget tree & obtain them more reliably than provider."
version: 1.0.2
repository: https://github.com/ArcaneArts/pylon
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  toxic_flutter: '>=1.0.1 <2.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
